### ISSUE TITLE
Unable to set value when using nextjs

### ISSUE THREAD

**Issue by morious** [niuware/mui-rte#80]
Hi,

I am trying to use mui-rte in a next js project. Whenever i try to assign a value to the value prop i am getting the following error:

Unexpected token a in JSON at position 0
SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at useEditorState (/Users/user/dev/test/mui-rte-test/node_modules/mui-rte/dist/index.js:1:14383)
    at /Users/user/dev/test/mui-rte-test/node_modules/mui-rte/dist/index.js:1:14629
    at useReducer (/Users/user/dev/test/mui-rte-test/node_modules/react-dom/cjs/react-dom-server.node.development.js:1361:57)
    at Object.useState (/Users/user/dev/test/mui-rte-test/node_modules/react-dom/cjs/react-dom-server.node.development.js:1299:10)
    at Object.useState (/Users/user/dev/test/mui-rte-test/node_modules/react/cjs/react.development.js:1637:21)
    at Object.MUIRichTextEditor [as render] (/Users/user/dev/test/mui-rte-test/node_modules/mui-rte/dist/index.js:1:14602)
    at ReactDOMServerRenderer.render (/Users/user/dev/test/mui-rte-test/node_modules/react-dom/cjs/react-dom-server.node.development.js:3795:44)
    at ReactDOMServerRenderer.read (/Users/user/dev/test/mui-rte-test/node_modules/react-dom/cjs/react-dom-server.node.development.js:3565:29)
    at renderToString (/Users/user/dev/test/mui-rte-test/node_modules/react-dom/cjs/react-dom-server.node.development.js:4296:27)
    at render (/Users/user/dev/test/mui-rte-test/node_modules/next/dist/next-server/server/render.js:81:16)
    at Object.renderPage (/Users/user/dev/test/mui-rte-test/node_modules/next/dist/next-server/server/render.js:346:16)
    at Function.getInitialProps (/Users/user/dev/test/mui-rte-test/.next/server/static/development/pages/_document.js:485:19)
    at Object.loadGetInitialProps (/Users/user/dev/test/mui-rte-test/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/Users/user/dev/test/mui-rte-test/node_modules/next/dist/next-server/server/render.js:350:36)
    at async DevServer.renderToHTML (/Users/user/dev/test/mui-rte-test/node_modules/next/dist/next-server/server/next-server.js:703:24)

Any idea what is going on?

Appreciate this project!!!

M

**Comment by morious** [comment]
Actually,

I continued to test with a regular react app with the following code:

import React, {useState} from 'react'
import MUIRichTextEditor from 'mui-rte';
const App = () => {
    const [state, setState] = useState({
        key: "defaultKey",
        value:"defaultContent"
    })
    return (
        <>
            <button onClick={() => setState({
                key: "newKey",
                value: "newContent"
            })}>
                Simulate new value arrived
            </button>
            <MUIRichTextEditor
                key={state.key}
                value={state.value}
            />
        </>
    )
}

export default App;

it is failing all the same.

Thanks!

M
